#!/usr/bin/env bash
# Idempotent local-developer setup for the ReportService .NET 8 project.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"

# 1. Verify .NET 8 SDK is available.
if ! command -v dotnet >/dev/null 2>&1; then
    echo "error: 'dotnet' not found on PATH." >&2
    case "$(uname -s)" in
        Darwin)
            echo "hint:  install the .NET 8 SDK, e.g.  brew install --cask dotnet-sdk" >&2
            ;;
        Linux)
            echo "hint:  install the .NET 8 SDK, e.g.  sudo apt-get update && sudo apt-get install -y dotnet-sdk-8.0" >&2
            ;;
        *)
            echo "hint:  install the .NET 8 SDK from https://dotnet.microsoft.com/download/dotnet/8.0" >&2
            ;;
    esac
    exit 1
fi

DOTNET_MAJOR="$(dotnet --version 2>/dev/null | cut -d. -f1 || echo 0)"
if [ "${DOTNET_MAJOR}" -lt 8 ]; then
    echo "error: .NET SDK 8.x is required; found $(dotnet --version)." >&2
    case "$(uname -s)" in
        Darwin)
            echo "hint:  brew install --cask dotnet-sdk" >&2
            ;;
        Linux)
            echo "hint:  sudo apt-get install -y dotnet-sdk-8.0" >&2
            ;;
    esac
    exit 1
fi

echo "==> Using dotnet $(dotnet --version)"

# 2. Restore NuGet packages (solution-wide, so Core / ingestion / admin all resolve together).
echo "==> Restoring NuGet packages"
(cd "$REPO_DIR" && dotnet restore)

# 3. Create .env with generated API keys, only if missing.
ENV_FILE="$REPO_DIR/.env"
gen_key() {
    if command -v openssl >/dev/null 2>&1; then
        openssl rand -hex 32
    elif [ -r /dev/urandom ]; then
        LC_ALL=C tr -dc 'a-f0-9' < /dev/urandom | head -c 64
    else
        echo "error: unable to generate a random key (no openssl and no /dev/urandom)." >&2
        exit 1
    fi
}

if [ ! -f "$ENV_FILE" ]; then
    echo "==> Generating $ENV_FILE with fresh API and admin keys"
    SDK_KEY="$(gen_key)"
    ADMIN_KEY="$(gen_key)"

    umask 077
    cat > "$ENV_FILE" <<EOF
# Local development env for ReportService.
# Auto-generated by scripts/setup.sh. Do NOT commit this file.
# Override any option via <Section>__<PropertyName>.

# Ingestion API — shared with mobile SDKs (sent in the 'apiKey' request header).
ReportService__ApiKey=${SDK_KEY}

# Admin UI — separate secret for human operators (entered on /Login).
Admin__AdminKey=${ADMIN_KEY}

# Uncomment and edit any of the following to override appsettings.json defaults.
#ReportService__ReportsRoot=reports
#ReportService__MaxUploadBytes=524288000
#ReportService__AllowedPlatforms__0=android
#ReportService__AllowedPlatforms__1=ios
#ReportService__RateLimitPermitsPerMinute=120
#ReportService__Storage=FileSystem
#ReportService__SqliteDbPath=reports.db
#Admin__SessionMinutes=60
EOF
    chmod 600 "$ENV_FILE"
else
    echo "==> $ENV_FILE already exists; leaving it unchanged"
fi

# 4. Best-effort HTTPS dev cert trust. Never fail the overall script.
echo "==> Trusting ASP.NET Core HTTPS dev cert (best effort)"
if ! dotnet dev-certs https --trust >/dev/null 2>&1; then
    echo "    (dev-certs step skipped or failed; continuing)"
fi

cat <<'EOF'

Setup complete.

Next steps:
  ./scripts/run.sh           # starts the ingestion API with values from .env loaded
  ./scripts/run.sh admin     # starts the admin UI (separate process, loopback port)
EOF
