#!/usr/bin/env bash
# Idempotent local-developer setup for the ReportService .NET 8 project.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"

# 1. Verify .NET 8 SDK is available.
if ! command -v dotnet >/dev/null 2>&1; then
    echo "error: 'dotnet' not found on PATH." >&2
    case "$(uname -s)" in
        Darwin)
            echo "hint:  install the .NET 8 SDK, e.g.  brew install --cask dotnet-sdk" >&2
            ;;
        Linux)
            echo "hint:  install the .NET 8 SDK, e.g.  sudo apt-get update && sudo apt-get install -y dotnet-sdk-8.0" >&2
            ;;
        *)
            echo "hint:  install the .NET 8 SDK from https://dotnet.microsoft.com/download/dotnet/8.0" >&2
            ;;
    esac
    exit 1
fi

DOTNET_MAJOR="$(dotnet --version 2>/dev/null | cut -d. -f1 || echo 0)"
if [ "${DOTNET_MAJOR}" -lt 8 ]; then
    echo "error: .NET SDK 8.x is required; found $(dotnet --version)." >&2
    case "$(uname -s)" in
        Darwin)
            echo "hint:  brew install --cask dotnet-sdk" >&2
            ;;
        Linux)
            echo "hint:  sudo apt-get install -y dotnet-sdk-8.0" >&2
            ;;
    esac
    exit 1
fi

echo "==> Using dotnet $(dotnet --version)"

# 2. Restore NuGet packages (solution-wide, so Core / ingestion / admin all resolve together).
echo "==> Restoring NuGet packages"
(cd "$REPO_DIR" && dotnet restore)

# 3. Create .env with generated API keys, only if missing.
ENV_FILE="$REPO_DIR/.env"
gen_key() {
    if command -v openssl >/dev/null 2>&1; then
        openssl rand -hex 32
    elif [ -r /dev/urandom ]; then
        LC_ALL=C tr -dc 'a-f0-9' < /dev/urandom | head -c 64
    else
        echo "error: unable to generate a random key (no openssl and no /dev/urandom)." >&2
        exit 1
    fi
}

if [ ! -f "$ENV_FILE" ]; then
    echo "==> Generating $ENV_FILE with fresh API, admin and analytics-pepper keys"
    SDK_KEY="$(gen_key)"
    ADMIN_KEY="$(gen_key)"
    ANALYTICS_PEPPER="$(gen_key)"

    umask 077
    cat > "$ENV_FILE" <<EOF
# Local development env for ReportService.
# Auto-generated by scripts/setup.sh. Do NOT commit this file.
# Override any option via <Section>__<PropertyName>.

# Ingestion API — shared with mobile SDKs (sent in the 'apiKey' request header).
ReportService__ApiKey=${SDK_KEY}

# Admin UI — separate secret for human operators (entered on /Login).
Admin__AdminKey=${ADMIN_KEY}

# Analytics — pepper mixed into the SHA-256 of every anonymousId before storage. The merged host's
# analytics pipeline REFUSES TO BOOT in Production without it (RSCSecretValidation), so generate it
# up front; the dev compose stack needs it too once ASPNETCORE_ENVIRONMENT=Production.
Analytics__IdentifierHashPepper=${ANALYTICS_PEPPER}

# Uncomment and edit any of the following to override appsettings.json defaults.
#ReportService__ReportsRoot=reports
#ReportService__MaxUploadBytes=524288000
#ReportService__AllowedPlatforms__0=android
#ReportService__AllowedPlatforms__1=ios
#ReportService__RateLimitPermitsPerMinute=120
#ReportService__Storage=FileSystem
#ReportService__SqliteDbPath=reports.db
#Admin__SessionMinutes=60
# Tenancy catalog (apps/environments/clients). Strict validation is on by default; set false to
# stamp+default but never reject during a phased client onboarding.
#Catalog__Enabled=true
EOF
    chmod 600 "$ENV_FILE"
else
    echo "==> $ENV_FILE already exists; leaving it unchanged"
fi

# 4. Best-effort HTTPS dev cert trust. Never fail the overall script.
echo "==> Trusting ASP.NET Core HTTPS dev cert (best effort)"
if ! dotnet dev-certs https --trust >/dev/null 2>&1; then
    echo "    (dev-certs step skipped or failed; continuing)"
fi

cat <<'EOF'

Setup complete.

Next steps (Docker Compose is the supported runtime — see CLAUDE.md / docs/guide/02-quickstart.md):
  ./scripts/run.sh                                # build + start the merged host on :8082
  # …or directly:
  HOST_PORT=8082 docker compose up --build -d     # 8080=prod, 18080=staging, 8082=this dev box
  docker compose logs -f                          # tail
Then open http://localhost:8082
EOF
