#!/usr/bin/env bash
#
# Syncs the tracked Postman collection against the generated OpenAPI spec.
#
#   spec  : docs/openapi/ingestion-v1.json   (generated by scripts/generate-docs.sh, gitignored)
#   target: postman/report-service.postman_collection.json   (tracked, hand-curated)
#
# The collection is the source of truth: it carries hand-written test scripts, request fixtures,
# the DevAutoSignIn flow, and admin-only NDJSON export requests that never appear in the ingestion
# OpenAPI spec. So this is an ADDITIVE sync, not a regeneration:
#
#   * Every spec operation already present in a curated request is left untouched.
#   * Spec operations with no matching request are scaffolded into a single managed folder
#     ("OpenAPI (auto-generated — review)"), grouped by tag, with a typed JSON body skeleton
#     synthesised from the referenced component schema.
#   * Requests in the collection that aren't in the spec (health probes, admin sign-in, the
#     analytics-v2 ingestion + NDJSON exports) are reported and KEPT — never deleted.
#
# The managed folder is fully owned by this script: it is stripped and rebuilt on every run, so
# the sync is idempotent. Review scaffolded requests and move the keepers into a curated folder.
#
# Usage:
#   scripts/update-postman.sh              # sync; rewrite the collection if anything changed
#   scripts/update-postman.sh --check      # dry run; exit 1 if the collection is missing any
#                                          #   spec operation (CI drift gate). No writes.
#   scripts/update-postman.sh --generate   # regenerate the OpenAPI spec first (slow: builds the
#                                          #   solution + runs generate-docs.sh), then sync.
#   scripts/update-postman.sh --spec PATH --collection PATH   # override either path.
#
# Prerequisites: jq. The .NET 8 SDK is only needed when the spec must be generated.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"

SPEC="$REPO_DIR/docs/openapi/ingestion-v1.json"
COLLECTION="$REPO_DIR/postman/report-service.postman_collection.json"
MANAGED_FOLDER="OpenAPI (auto-generated — review)"

CHECK=0
GENERATE=0
while [ $# -gt 0 ]; do
    case "$1" in
        --check)      CHECK=1 ;;
        --generate)   GENERATE=1 ;;
        --spec)       SPEC="$2"; shift ;;
        --collection) COLLECTION="$2"; shift ;;
        -h|--help)    sed -n '2,33p' "$0" | sed 's/^# \{0,1\}//'; exit 0 ;;
        *)            echo "error: unknown argument '$1' (try --help)" >&2; exit 2 ;;
    esac
    shift
done

command -v jq >/dev/null 2>&1 || { echo "error: jq is required but not on PATH" >&2; exit 1; }
[ -f "$COLLECTION" ] || { echo "error: collection not found: $COLLECTION" >&2; exit 1; }

# --- 1. Make sure the OpenAPI spec exists ------------------------------------------------------
# docs/openapi/ is gitignored, so on a fresh clone the spec won't be there yet.
if [ "$GENERATE" -eq 1 ] || [ ! -f "$SPEC" ]; then
    if [ "$CHECK" -eq 1 ] && [ ! -f "$SPEC" ]; then
        echo "error: --check needs an existing spec at $SPEC (run scripts/generate-docs.sh first)" >&2
        exit 1
    fi
    if [ "$GENERATE" -eq 1 ]; then reason="refresh requested"; else reason="not found at $SPEC"; fi
    echo "==> OpenAPI spec $reason; running scripts/generate-docs.sh (this builds the solution)…"
    "$SCRIPT_DIR/generate-docs.sh"
fi
[ -f "$SPEC" ] || { echo "error: spec still not found after generation: $SPEC" >&2; exit 1; }

jq empty "$SPEC"       2>/dev/null || { echo "error: $SPEC is not valid JSON" >&2; exit 1; }
jq empty "$COLLECTION" 2>/dev/null || { echo "error: $COLLECTION is not valid JSON" >&2; exit 1; }

# --- 2. Which spec operations does the collection already cover? --------------------------------
# Normalise every curated request to "METHOD /path/with/{}" so a path variable matches regardless
# of whether it's written {{platform}} (Postman) or {platform} (OpenAPI). The managed folder is
# excluded so its own stubs never count as coverage.
present_keys() {
    jq -c --arg managed "$MANAGED_FOLDER" '
        [ (.item // []) | map(select(.name != $managed)) | .. | objects | select(has("request"))
          | .request
          | ((.method // "GET") | ascii_upcase) as $m
          | (((.url.path // []) | join("/"))
              | gsub("\\{\\{[^}]+\\}\\}"; "{}") | gsub("\\{[^}]+\\}"; "{}")) as $p
          | $m + " /" + $p ]
        | unique
    ' "$COLLECTION"
}

PRESENT="$(present_keys)"

# Flat list of every spec operation as {method, path, key, summary, tag, node}.
SPEC_OPS="$(jq -c '
    [ .paths | to_entries[] | .key as $path | .value | to_entries[]
      | select(.key | test("^(get|post|put|patch|delete)$"))
      | { method: (.key | ascii_upcase),
          path:   $path,
          key:    ((.key | ascii_upcase) + " " + ($path | gsub("\\{[^}]+\\}"; "{}"))),
          summary: (.value.summary // .value.operationId // ""),
          tag:    (.value.tags[0] // "untagged"),
          node:   .value } ]
' "$SPEC")"

MISSING_KEYS="$(jq -c --argjson present "$PRESENT" '[ .[] | select(.key as $k | ($present | index($k)) | not) ]' <<<"$SPEC_OPS")"
MISSING_COUNT="$(jq 'length' <<<"$MISSING_KEYS")"
SPEC_COUNT="$(jq 'length' <<<"$SPEC_OPS")"

# Collection requests that have no spec counterpart (kept, just reported).
COLLECTION_ONLY="$(jq -c --argjson spec "$SPEC_OPS" '
    [ .[] | select(. as $k | ($spec | map(.key) | index($k)) | not) ]
' <<<"$PRESENT")"

# --- 3. Report --------------------------------------------------------------------------------
echo "OpenAPI spec : $SPEC"
echo "Collection   : $COLLECTION"
echo
echo "Spec operations            : $SPEC_COUNT"
echo "Already covered            : $((SPEC_COUNT - MISSING_COUNT))"
echo "Missing from collection    : $MISSING_COUNT"
if [ "$MISSING_COUNT" -gt 0 ]; then
    jq -r '.[] | "    + " + .key + (if .summary != "" then "  — " + .summary else "" end)' <<<"$MISSING_KEYS"
fi
COLLECTION_ONLY_COUNT="$(jq 'length' <<<"$COLLECTION_ONLY")"
echo "Collection-only requests   : $COLLECTION_ONLY_COUNT (kept — not in the ingestion spec)"
if [ "$COLLECTION_ONLY_COUNT" -gt 0 ]; then
    jq -r '.[] | "    · " + .' <<<"$COLLECTION_ONLY"
fi
echo

# --- 4. --check: drift gate, no writes --------------------------------------------------------
if [ "$CHECK" -eq 1 ]; then
    if [ "$MISSING_COUNT" -gt 0 ]; then
        echo "drift: collection is missing $MISSING_COUNT spec operation(s). Run scripts/update-postman.sh." >&2
        exit 1
    fi
    echo "OK — collection covers every spec operation."
    exit 0
fi

# --- 5. Build the managed folder of scaffolded requests ---------------------------------------
# Each missing operation carries its full spec node, so one pass builds the request + a body
# skeleton synthesised from the component schemas: $ref is resolved, objects become a property
# map, arrays a single-element list, scalars a typed zero value.
MANAGED="$(jq -c --argjson missing "$MISSING_KEYS" --argjson schemas "$(jq -c '.components.schemas // {}' "$SPEC")" --arg folder "$MANAGED_FOLDER" '
    def deref($s):
        if (type == "object" and has("$ref"))
        then ($s[(.["$ref"] | sub("^#/components/schemas/"; ""))] // {})
        else . end;
    def sample($s):
        deref($s) as $d
        | ( if   ($d.properties != null)                    then ($d.properties | map_values(sample($s)))
            elif  ($d.type == "object")                     then {}
            elif  ($d.type == "array")                      then [ (($d.items // {}) | sample($s)) ]
            elif  ($d.type == "integer" or $d.type == "number") then 0
            elif  ($d.type == "boolean")                    then false
            elif  ($d.type == "string")                     then ""
            else  null end );
    def postman_path: (split("/") | map(select(. != "")) | map(if test("^\\{.*\\}$") then ":" + .[1:-1] else . end));
    def path_vars:    (split("/") | map(select(test("^\\{.*\\}$"))) | map({ key: .[1:-1], value: "" }));

    { name: $folder,
      description: "Auto-generated by scripts/update-postman.sh from docs/openapi. This folder is rebuilt on every run — do not hand-edit it; review scaffolded requests and move the keepers into a curated folder.",
      item: ( $missing
              | group_by(.tag)
              | map({
                  name: .[0].tag,
                  item: map(
                      . as $op
                      | ($op.node.requestBody.content // {}) as $content
                      | { name: (if $op.summary != "" then $op.summary else ($op.method + " " + $op.path) end),
                          request: ({
                              method: $op.method,
                              header: (if ($content."application/json") then [ { key: "Content-Type", value: "application/json" } ] else [] end),
                              url: ({
                                  raw:  ("{{baseUrl}}/" + (($op.path | postman_path) | join("/"))),
                                  host: ["{{baseUrl}}"],
                                  path: ($op.path | postman_path)
                              } + (if (($op.path | path_vars) | length) > 0 then { variable: ($op.path | path_vars) } else {} end))
                          }
                          + (if ($content."application/json") then
                                { body: { mode: "raw",
                                          raw: (($content."application/json".schema // {}) | sample($schemas) | tojson),
                                          options: { raw: { language: "json" } } } }
                             elif ($content."multipart/form-data") then
                                { body: { mode: "formdata",
                                          formdata: [ { key: "json", value: "{}", type: "text", contentType: "application/json" } ] } }
                             else {} end)),
                          description: (($op.node.description // $op.summary // "") + "\n\nAuto-generated stub — review, add tests, then move into a curated folder." | ltrimstr("\n\n"))
                        }
                  )
                }) ) }
' <<<"$SPEC_OPS")"

# --- 6. Merge: strip any previous managed folder, append the fresh one if non-empty -----------
TMP="$(mktemp "${TMPDIR:-/tmp}/postman-sync.XXXXXX.json")"
trap 'rm -f "$TMP"' EXIT

jq --argjson managed "$MANAGED" --arg name "$MANAGED_FOLDER" '
    .item |= (map(select(.name != $name))
              + (if (($managed.item | length) > 0) then [ $managed ] else [] end))
' "$COLLECTION" > "$TMP"

# Only rewrite the tracked file when the *content* actually changed — compare canonical (sorted,
# normalised) JSON so jq's reformatting alone never produces a spurious diff on the curated file.
if [ "$(jq -S . "$TMP")" = "$(jq -S . "$COLLECTION")" ]; then
    echo "No changes — collection already in sync with the spec."
else
    cp "$TMP" "$COLLECTION"
    echo "Wrote $MISSING_COUNT scaffolded request(s) into \"$MANAGED_FOLDER\" in:"
    echo "  $COLLECTION"
    echo "(The file is normalised to jq's 2-space formatting on write.)"
    echo "Review the scaffolded requests, add tests/bodies, then move the keepers into a curated folder and re-import."
fi
